# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locale.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.artifacts.usagestats_pb.privacy_pb2 as privacy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='locale.proto',
  package='android.content',
  syntax='proto2',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x0clocale.proto\x12\x0f\x61ndroid.content\x1a\rprivacy.proto\"^\n\x0bLocaleProto\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x0f\n\x07variant\x18\x03 \x01(\t\x12\x0e\n\x06script\x18\x04 \x01(\t:\x0b\x18\x01\x9a\x9f\xd5\x87\x03\x03\x08\xc8\x01\x42\x02P\x01')
  ,
  dependencies=[privacy__pb2.DESCRIPTOR,])




_LOCALEPROTO = _descriptor.Descriptor(
  name='LocaleProto',
  full_name='android.content.LocaleProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='android.content.LocaleProto.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='android.content.LocaleProto.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variant', full_name='android.content.LocaleProto.variant', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='script', full_name='android.content.LocaleProto.script', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\030\001\232\237\325\207\003\003\010\310\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['LocaleProto'] = _LOCALEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocaleProto = _reflection.GeneratedProtocolMessageType('LocaleProto', (_message.Message,), dict(
  DESCRIPTOR = _LOCALEPROTO,
  __module__ = 'locale_pb2'
  # @@protoc_insertion_point(class_scope:android.content.LocaleProto)
  ))
_sym_db.RegisterMessage(LocaleProto)


DESCRIPTOR._options = None
_LOCALEPROTO._options = None
# @@protoc_insertion_point(module_scope)
