# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: privacy.proto
import sys
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

if sys.version_info >= (3, 9):
  from google.protobuf import descriptor_pb2  as descriptor__pb2
else:
  from . import descriptor_pb2  as descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='privacy.proto',
  package='android',
  syntax='proto2',
  serialized_options=b'\n\024com.android.incidentP\001',
  serialized_pb=b'\n\rprivacy.proto\x12\x07\x61ndroid\x1a\x10\x64\x65scriptor.proto\"P\n\x0cPrivacyFlags\x12.\n\x04\x64\x65st\x18\x01 \x01(\x0e\x32\x14.android.Destination:\nDEST_UNSET\x12\x10\n\x08patterns\x18\x02 \x03(\t*V\n\x0b\x44\x65stination\x12\x0e\n\nDEST_LOCAL\x10\x00\x12\x11\n\rDEST_EXPLICIT\x10\x64\x12\x13\n\x0e\x44\x45ST_AUTOMATIC\x10\xc8\x01\x12\x0f\n\nDEST_UNSET\x10\xff\x01:H\n\x07privacy\x12\x1d.google.protobuf.FieldOptions\x18\xf3\xd3\xfa\x30 \x01(\x0b\x32\x15.android.PrivacyFlags:N\n\x0bmsg_privacy\x12\x1f.google.protobuf.MessageOptions\x18\xf3\xd3\xfa\x30 \x01(\x0b\x32\x15.android.PrivacyFlagsB\x18\n\x14\x63om.android.incidentP\x01'
  ,
  dependencies=[descriptor__pb2.DESCRIPTOR,])

_DESTINATION = _descriptor.EnumDescriptor(
  name='Destination',
  full_name='android.Destination',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEST_LOCAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEST_EXPLICIT', index=1, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEST_AUTOMATIC', index=2, number=200,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEST_UNSET', index=3, number=255,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=126,
  serialized_end=212,
)
_sym_db.RegisterEnumDescriptor(_DESTINATION)

Destination = enum_type_wrapper.EnumTypeWrapper(_DESTINATION)
DEST_LOCAL = 0
DEST_EXPLICIT = 100
DEST_AUTOMATIC = 200
DEST_UNSET = 255

PRIVACY_FIELD_NUMBER = 102672883
privacy = _descriptor.FieldDescriptor(
  name='privacy', full_name='android.privacy', index=0,
  number=102672883, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
MSG_PRIVACY_FIELD_NUMBER = 102672883
msg_privacy = _descriptor.FieldDescriptor(
  name='msg_privacy', full_name='android.msg_privacy', index=1,
  number=102672883, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_PRIVACYFLAGS = _descriptor.Descriptor(
  name='PrivacyFlags',
  full_name='android.PrivacyFlags',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dest', full_name='android.PrivacyFlags.dest', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=255,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patterns', full_name='android.PrivacyFlags.patterns', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=124,
)

_PRIVACYFLAGS.fields_by_name['dest'].enum_type = _DESTINATION
DESCRIPTOR.message_types_by_name['PrivacyFlags'] = _PRIVACYFLAGS
DESCRIPTOR.enum_types_by_name['Destination'] = _DESTINATION
DESCRIPTOR.extensions_by_name['privacy'] = privacy
DESCRIPTOR.extensions_by_name['msg_privacy'] = msg_privacy
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrivacyFlags = _reflection.GeneratedProtocolMessageType('PrivacyFlags', (_message.Message,), {
  'DESCRIPTOR' : _PRIVACYFLAGS,
  '__module__' : 'privacy_pb2'
  # @@protoc_insertion_point(class_scope:android.PrivacyFlags)
  })
_sym_db.RegisterMessage(PrivacyFlags)

privacy.message_type = _PRIVACYFLAGS
descriptor__pb2.FieldOptions.RegisterExtension(privacy)
msg_privacy.message_type = _PRIVACYFLAGS
descriptor__pb2.MessageOptions.RegisterExtension(msg_privacy)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
