# -*- coding: utf-8 -*-
# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: privacy.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprivacy.proto\x12\x07\x61ndroid\x1a google/protobuf/descriptor.proto\"P\n\x0cPrivacyFlags\x12.\n\x04\x64\x65st\x18\x01 \x01(\x0e\x32\x14.android.Destination:\nDEST_UNSET\x12\x10\n\x08patterns\x18\x02 \x03(\t*V\n\x0b\x44\x65stination\x12\x0e\n\nDEST_LOCAL\x10\x00\x12\x11\n\rDEST_EXPLICIT\x10\x64\x12\x13\n\x0e\x44\x45ST_AUTOMATIC\x10\xc8\x01\x12\x0f\n\nDEST_UNSET\x10\xff\x01:H\n\x07privacy\x12\x1d.google.protobuf.FieldOptions\x18\xf3\xd3\xfa\x30 \x01(\x0b\x32\x15.android.PrivacyFlags:N\n\x0bmsg_privacy\x12\x1f.google.protobuf.MessageOptions\x18\xf3\xd3\xfa\x30 \x01(\x0b\x32\x15.android.PrivacyFlagsB\x18\n\x14\x63om.android.incidentP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'privacy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.android.incidentP\001'
  _globals['_DESTINATION']._serialized_start=142
  _globals['_DESTINATION']._serialized_end=228
  _globals['_PRIVACYFLAGS']._serialized_start=60
  _globals['_PRIVACYFLAGS']._serialized_end=140
# @@protoc_insertion_point(module_scope)
