# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: window_configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import scripts.artifacts.usagestats_pb.rect_pb2 as rect__pb2
import scripts.artifacts.usagestats_pb.privacy_pb2 as privacy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='window_configuration.proto',
  package='android.app',
  syntax='proto2',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x1awindow_configuration.proto\x12\x0b\x61ndroid.app\x1a\nrect.proto\x1a\rprivacy.proto\"\xb2\x01\n\x18WindowConfigurationProto\x12/\n\napp_bounds\x18\x01 \x01(\x0b\x32\x1b.android.graphics.RectProto\x12\x16\n\x0ewindowing_mode\x18\x02 \x01(\x05\x12\x15\n\ractivity_type\x18\x03 \x01(\x05\x12+\n\x06\x62ounds\x18\x04 \x01(\x0b\x32\x1b.android.graphics.RectProto:\t\x9a\x9f\xd5\x87\x03\x03\x08\xc8\x01\x42\x02P\x01')
  ,
  dependencies=[rect__pb2.DESCRIPTOR,privacy__pb2.DESCRIPTOR,])




_WINDOWCONFIGURATIONPROTO = _descriptor.Descriptor(
  name='WindowConfigurationProto',
  full_name='android.app.WindowConfigurationProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_bounds', full_name='android.app.WindowConfigurationProto.app_bounds', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='windowing_mode', full_name='android.app.WindowConfigurationProto.windowing_mode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activity_type', full_name='android.app.WindowConfigurationProto.activity_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounds', full_name='android.app.WindowConfigurationProto.bounds', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\232\237\325\207\003\003\010\310\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=249,
)

_WINDOWCONFIGURATIONPROTO.fields_by_name['app_bounds'].message_type = rect__pb2._RECTPROTO
_WINDOWCONFIGURATIONPROTO.fields_by_name['bounds'].message_type = rect__pb2._RECTPROTO
DESCRIPTOR.message_types_by_name['WindowConfigurationProto'] = _WINDOWCONFIGURATIONPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WindowConfigurationProto = _reflection.GeneratedProtocolMessageType('WindowConfigurationProto', (_message.Message,), dict(
  DESCRIPTOR = _WINDOWCONFIGURATIONPROTO,
  __module__ = 'window_configuration_pb2'
  # @@protoc_insertion_point(class_scope:android.app.WindowConfigurationProto)
  ))
_sym_db.RegisterMessage(WindowConfigurationProto)


DESCRIPTOR._options = None
_WINDOWCONFIGURATIONPROTO._options = None
# @@protoc_insertion_point(module_scope)
