# -*- coding: utf-8 -*-
# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: window_configuration.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import rect_pb2 as rect__pb2
from . import privacy_pb2 as privacy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1awindow_configuration.proto\x12\x0b\x61ndroid.app\x1a\nrect.proto\x1a\rprivacy.proto\"\xb2\x01\n\x18WindowConfigurationProto\x12/\n\napp_bounds\x18\x01 \x01(\x0b\x32\x1b.android.graphics.RectProto\x12\x16\n\x0ewindowing_mode\x18\x02 \x01(\x05\x12\x15\n\ractivity_type\x18\x03 \x01(\x05\x12+\n\x06\x62ounds\x18\x04 \x01(\x0b\x32\x1b.android.graphics.RectProto:\t\x9a\x9f\xd5\x87\x03\x03\x08\xc8\x01\x42\x02P\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'window_configuration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_WINDOWCONFIGURATIONPROTO']._options = None
  _globals['_WINDOWCONFIGURATIONPROTO']._serialized_options = b'\232\237\325\207\003\003\010\310\001'
  _globals['_WINDOWCONFIGURATIONPROTO']._serialized_start=71
  _globals['_WINDOWCONFIGURATIONPROTO']._serialized_end=249
# @@protoc_insertion_point(module_scope)
