# -*- coding: utf-8 -*-
# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_snapshot.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13task_snapshot.proto\x12\x15\x63om.android.server.wm\"\x86\x04\n\x11TaskSnapshotProto\x12\x13\n\x0borientation\x18\x01 \x01(\x05\x12\x12\n\ninset_left\x18\x02 \x01(\x05\x12\x11\n\tinset_top\x18\x03 \x01(\x05\x12\x13\n\x0binset_right\x18\x04 \x01(\x05\x12\x14\n\x0cinset_bottom\x18\x05 \x01(\x05\x12\x18\n\x10is_real_snapshot\x18\x06 \x01(\x08\x12\x16\n\x0ewindowing_mode\x18\x07 \x01(\x05\x12 \n\x14system_ui_visibility\x18\x08 \x01(\x05\x42\x02\x18\x01\x12\x16\n\x0eis_translucent\x18\t \x01(\x08\x12\x1e\n\x16top_activity_component\x18\n \x01(\t\x12\x18\n\x0clegacy_scale\x18\x0b \x01(\x02\x42\x02\x18\x01\x12\n\n\x02id\x18\x0c \x01(\x03\x12\x10\n\x08rotation\x18\r \x01(\x05\x12\x12\n\ntask_width\x18\x0e \x01(\x05\x12\x13\n\x0btask_height\x18\x0f \x01(\x05\x12\x12\n\nappearance\x18\x10 \x01(\x05\x12\x1c\n\x14letterbox_inset_left\x18\x11 \x01(\x05\x12\x1b\n\x13letterbox_inset_top\x18\x12 \x01(\x05\x12\x1d\n\x15letterbox_inset_right\x18\x13 \x01(\x05\x12\x1e\n\x16letterbox_inset_bottom\x18\x14 \x01(\x05\x12\x0f\n\x07ui_mode\x18\x15 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_snapshot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKSNAPSHOTPROTO'].fields_by_name['system_ui_visibility']._options = None
  _globals['_TASKSNAPSHOTPROTO'].fields_by_name['system_ui_visibility']._serialized_options = b'\030\001'
  _globals['_TASKSNAPSHOTPROTO'].fields_by_name['legacy_scale']._options = None
  _globals['_TASKSNAPSHOTPROTO'].fields_by_name['legacy_scale']._serialized_options = b'\030\001'
  _globals['_TASKSNAPSHOTPROTO']._serialized_start=47
  _globals['_TASKSNAPSHOTPROTO']._serialized_end=565
# @@protoc_insertion_point(module_scope)
