"""Synthetic SwiftKey contract tests; native integration is explicitly opt-in.

The ZIP contains a real binary model generated by SwiftKey 9.10.49.20's engine,
its unmodified native export, and explicit synthetic tokens. Nothing came from
a device. Expected counts are calculated from the corpus, not from the decoder.
"""
from collections import Counter
import copy
import fnmatch
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch
import zipfile

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from scripts.artifacts import swiftkey  # pylint: disable=wrong-import-position
from scripts.context import Context  # pylint: disable=wrong-import-position
from scripts import swiftkey_lm as native_reader  # pylint: disable=wrong-import-position
from scripts.swiftkey_lm import (  # pylint: disable=wrong-import-position
    BACKEND_ENV, SwiftKeyLMError, backend_directory, decode_export, extract_model, sha256_file,
)

FIXTURE = REPO_ROOT / 'admin/test/cases/data/swiftkey/synthetic_9_10_49_20.zip'
MODEL_MEMBER = 'data/data/com.touchtype.swiftkey/files/language_models/user/dynamic.lm'


def fixture_data():
    """Load known synthetic input and native output without extracting paths."""
    with zipfile.ZipFile(FIXTURE) as archive:
        return (json.loads(archive.read('native_export.json')),
                [json.loads(line) for line in archive.read('corpus.jsonl').decode('utf-8').splitlines()],
                archive.read(MODEL_MEMBER))


class SwiftKeyFormatTests(unittest.TestCase):
    """Assertions against independent corpus and malformed native structures."""

    def setUp(self):
        self.raw, self.corpus, _binary = fixture_data()

    def test_ngrams_match_independent_corpus_and_unicode(self):
        expected = Counter()
        for sequence in self.corpus:
            for order in range(1, 4):
                for start in range(len(sequence) - order + 1):
                    expected[tuple(sequence[start:start + order])] += 1
        model = decode_export(self.raw)
        observed = {tuple(item['terms']): item['model_count'] for item in model['ngrams']}
        self.assertEqual(observed, dict(expected))
        self.assertEqual(model['term_count'], 17)
        self.assertEqual(model['ngram_node_count'], 37)
        self.assertIn('🔬testwort', {item['text'] for item in model['terms']})
        self.assertEqual(observed[('synthetikwolke', 'pruefwortalpha', 'synthetikwolke')], 3)

    def test_utf16_pair_cannot_split_surrogate(self):
        self.raw['model']['word_data'] = '🔬'
        self.raw['model']['words'][0] = [0, 1]
        with self.assertRaises(SwiftKeyLMError):
            decode_export(self.raw)

    def test_corrupt_structures_are_rejected(self):
        mutations = [
            ('words', [[999999, 1]]),
            ('encoding_sets', [[False, 0]] * 17),
            ('ngram_nodes', [[1, 0, 1]]),
            ('ngram_nodes', [[1, 99999, 0]]),
            ('ngram_nodes', [[True, 0, 0]]),
            ('ngram_nodes', [[1, 0, 0], [1, 0, 1]]),
        ]
        for field, value in mutations:
            with self.subTest(field=field, value=value):
                raw = copy.deepcopy(self.raw)
                raw['model'][field] = value
                with self.assertRaises(SwiftKeyLMError):
                    decode_export(raw)

    def test_empty_export_is_success_and_times_remain_raw(self):
        raw = {'model': {'word_data': '', 'words': [], 'encoding_sets': [],
                         'encodings': [], 'ngram_nodes': []},
               'first_trained_unix_seconds': 0, 'last_trained_unix_seconds': 0,
               'native_ngram_export_present': False}
        model = decode_export(raw)
        self.assertEqual(model['term_count'], 0)
        self.assertEqual(model['ngrams'], [])
        self.assertIsNone(model['first_trained_utc'])
        raw.update(first_trained_unix_seconds=200, last_trained_unix_seconds=100)
        model = decode_export(raw)
        self.assertEqual(model['first_trained_raw'], 200)
        self.assertIsNone(model['first_trained_utc'])

    def test_path_anchor_matches_android_users_and_rejects_other_stores(self):
        pattern = swiftkey.__artifacts_v2__['swiftkey_model_words']['paths'][0]
        for prefix in ['root/data/data/', 'root/data/user/0/', 'root/data/user/10/']:
            self.assertTrue(fnmatch.fnmatchcase(prefix + MODEL_MEMBER.split('data/data/')[1], pattern))
        self.assertFalse(fnmatch.fnmatchcase('root/' + MODEL_MEMBER + '.backup', pattern))
        self.assertFalse(fnmatch.fnmatchcase('root/' + MODEL_MEMBER.replace('swiftkey/', 'swiftkey.beta/'), pattern))

    def test_missing_backend_is_explicit_and_imports_are_optional(self):
        with patch.dict(os.environ, {}, clear=True):
            with self.assertRaisesRegex(SwiftKeyLMError, BACKEND_ENV):
                backend_directory()


class SwiftKeyArtifactTests(unittest.TestCase):
    """Real ALEAPP Context, source scoping and status rows without native dependency."""

    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='swiftkey_artifact_test_')
        self.root = Path(self.temporary.name)
        self.model_path = self.root / MODEL_MEMBER
        self.model_path.parent.mkdir(parents=True)
        raw, _corpus, binary = fixture_data()
        self.model_path.write_bytes(binary)
        self.model = decode_export(raw)
        self.model.update(sha256=sha256_file(self.model_path), size_bytes=len(binary),
                          outer_declared_size=0, input_content_unchanged=True, mtime_unchanged=True,
                          engine_version=raw['engine_version'], engine_source_version=raw['engine_source_version'],
                          engine_sha256='synthetic-test-value', adapter_sha256='synthetic-test-value')
        Context.clear()
        Context.set_data_folder(str(self.root))
        Context.set_report_folder(str(self.root / 'reports'))
        Context.set_files_found([str(self.model_path), str(self.model_path)])

    def tearDown(self):
        Context.clear()
        Context.set_data_folder(None)
        self.temporary.cleanup()

    def test_words_ngrams_and_metadata_deduplicate_source_paths(self):
        with patch.object(swiftkey, 'extract_model', return_value=self.model) as exporter:
            for function, count in [(swiftkey.swiftkey_model_words, 17),
                                    (swiftkey.swiftkey_model_ngrams, 20),
                                    (swiftkey.swiftkey_model_metadata, 1)]:
                headers, rows, source = function.__wrapped__(Context)
                self.assertEqual(len(rows), count)
                self.assertEqual(source, str(self.model_path))
                for row in rows:
                    self.assertEqual(len(row), len(headers))
                    self.assertEqual(row[-1], MODEL_MEMBER)
                self.assertEqual(exporter.call_count, 1)
                exporter.reset_mock()

    def test_multiple_accounts_keep_per_row_source_and_hash(self):
        other = self.root / MODEL_MEMBER.replace('data/data/', 'data/user/10/')
        other.parent.mkdir(parents=True)
        shutil.copyfile(self.model_path, other)
        Context.set_files_found([str(self.model_path), str(other)])
        with patch.object(swiftkey, 'extract_model', return_value=self.model):
            _headers, rows, _source = swiftkey.swiftkey_model_words.__wrapped__(Context)
        self.assertEqual(len(rows), 34)
        self.assertEqual({row[-1] for row in rows}, {MODEL_MEMBER, str(other.relative_to(self.root))})

    def test_failure_is_metadata_error_and_does_not_discard_other_models(self):
        other = self.root / MODEL_MEMBER.replace('data/data/', 'data/user/10/')
        other.parent.mkdir(parents=True)
        other.write_bytes(b'bad fixture')
        Context.set_files_found([str(self.model_path), str(other)])
        with patch.object(swiftkey, 'extract_model', side_effect=[self.model, SwiftKeyLMError('test failure')]), \
                patch.object(swiftkey, 'logfunc'):
            headers, rows, _source = swiftkey.swiftkey_model_metadata.__wrapped__(Context)
        self.assertEqual([row[0] for row in rows], ['exported', 'error'])
        self.assertEqual(rows[1][-2], 'test failure')
        self.assertEqual(len(headers), len(rows[1]))

    def test_unrelated_or_missing_file_returns_result_triple(self):
        Context.set_files_found([str(self.root / 'dynamic.lm')])
        for function in [swiftkey.swiftkey_model_words, swiftkey.swiftkey_model_ngrams,
                         swiftkey.swiftkey_model_metadata]:
            headers, rows, source = function.__wrapped__(Context)
            self.assertTrue(headers)
            self.assertEqual(rows, [])
            self.assertEqual(source, '')
        Context.set_files_found([])
        self.assertEqual(swiftkey.swiftkey_model_words.__wrapped__(Context)[1], [])


class SwiftKeySnapshotTests(unittest.TestCase):
    """Fail closed if evidence changes, or if the native process does not finish."""

    def test_source_change_during_native_export_is_rejected(self):
        raw, _corpus, binary = fixture_data()
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / 'dynamic.lm'
            source.write_bytes(binary)

            def fake_export(command, **_kwargs):
                Path(command[-1]).write_text(json.dumps(raw), encoding='utf-8')
                source.write_bytes(binary + b'changed')
                return subprocess.CompletedProcess(command, 0, '', '')

            with patch.object(native_reader, 'backend_directory', return_value=root), \
                    patch.object(native_reader, 'find_java', return_value='java'), \
                    patch.object(native_reader.subprocess, 'run', side_effect=fake_export):
                with self.assertRaisesRegex(SwiftKeyLMError, 'Source content changed'):
                    extract_model(source)

    def test_timeout_is_explicit_and_source_is_unchanged(self):
        _raw, _corpus, binary = fixture_data()
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / 'dynamic.lm'
            source.write_bytes(binary)
            before = sha256_file(source)
            with patch.object(native_reader, 'backend_directory', return_value=root), \
                    patch.object(native_reader, 'find_java', return_value='java'), \
                    patch.object(native_reader.subprocess, 'run',
                                 side_effect=subprocess.TimeoutExpired('synthetic-native-test', 1)):
                with self.assertRaisesRegex(SwiftKeyLMError, 'timed out'):
                    extract_model(source, timeout=1)
            self.assertEqual(sha256_file(source), before)


@unittest.skipUnless(os.environ.get(BACKEND_ENV), 'Optional native backend not configured')
class SwiftKeyNativeIntegrationTests(unittest.TestCase):
    """Exercise the actual original engine when an external backend is configured."""

    def test_native_export_matches_corpus_and_preserves_source(self):
        raw, corpus, binary = fixture_data()
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / 'dynamic.lm'
            source.write_bytes(binary)
            before = source.stat()
            model = extract_model(source)
            self.assertTrue(model['input_content_unchanged'])
            self.assertEqual(before.st_mtime_ns, source.stat().st_mtime_ns)
            self.assertEqual(model['terms'], decode_export(raw)['terms'])
            expected = Counter()
            for sequence in corpus:
                for order in range(1, 4):
                    for start in range(len(sequence) - order + 1):
                        expected[tuple(sequence[start:start + order])] += 1
            self.assertEqual({tuple(item['terms']): item['model_count'] for item in model['ngrams']}, dict(expected))
            source.write_bytes(binary[:128])
            with self.assertRaises(SwiftKeyLMError):
                extract_model(source)
            source.write_bytes(b'not a valid language model')
            with self.assertRaisesRegex(SwiftKeyLMError, 'signature'):
                extract_model(source)


if __name__ == '__main__':
    unittest.main()
