__artifacts_v2__ = {
    "nova_chatbot_history_detail": {
        "name": "Nova AI Chatbot - Message Detail",
        "description": (
            "Extracts every individual message from the AI Chatbot - Nova app "
            "(com.scaleup.chatai) from the HistoryDetail table. "
            "Each row represents one message and is enriched with parent conversation "
            "context joined from History: conversation title, AI model used, and "
            "soft-deleted status. Three attachment presence flags are added via "
            "correlated EXISTS subqueries against HistoryDetailImage, "
            "HistoryDetailDocument, and HistoryDetailLink, indicating whether each "
            "message has an associated image, document, or link without duplicating "
            "rows or loading attachment content. "
            "Enables message-level timeline reconstruction and rapid attachment triage "
            "across all conversations."
        ),
        "author": "Guilherme Guilherme",
        "version": "0.2",
        "date": "2025-04-27",
        "requirements": "none",
        "category": "AI Chatbot - Nova",
        "notes": (
            "Database: com.scaleup.chatai/databases/chat-ai.db. "
            "All timestamps (createdAt, lastModifiedAt) are stored as Unix milliseconds "
            "(INTEGER) and converted to UTC strings for display. "
            "HistoryDetail.type: 0 = USER (message sent by the device user), "
            "1 = ASSISTANT (response generated by the AI model). "
            "token counts reflect the number of tokens consumed by each message; "
            "ASSISTANT messages with 0 tokens typically indicate image-generation "
            "responses where no text tokens were billed. "
            "reasoningContent contains chain-of-thought reasoning text when the "
            "underlying model produces it (e.g. DeepSeek-R1 reasoning traces). "
            "has_image = Yes means at least one record exists in HistoryDetailImage "
            "for this message. "
            "has_document = Yes means at least one record exists in HistoryDetailDocument "
            "for this message — the user submitted a file to the AI. "
            "has_link = Yes means at least one record exists in HistoryDetailLink. "
            "softDeleted is inherited from the parent History record; DELETED means the "
            "conversation was removed by the user but all messages remain physically in "
            "the database and are forensically recoverable. "
            "syncState and syncRetryCount reflect cloud synchronisation status."
        ),
        "paths": ("*/com.scaleup.chatai/databases/chat-ai.db",),
        "function": "get_nova_chatbot_history_detail",
    }
}

import sqlite3
import datetime
from scripts.artifact_report import ArtifactHtmlReport
import scripts.ilapfuncs

# ---------------------------------------------------------------------------
# Known mappings for the chatBotModel integer field.
# Source: FirestoreHistory.EngineTypes enum ordinals from decompiled APK source
# (com.scaleup.chatai.ui.conversation.FirestoreHistory).
# The integer stored in the database is the ENUM ORDINAL (0-based position),
# NOT the botId from chatbotAgentMap. These are two independent systems.
# Image-generating engines: 3 (legacy Bard ordinal reused), 4, 12, 13, 17.
# NOTE: ordinal 3 ('bard') was reused for image generation in newer app versions;
# presence of HistoryDetailImage records confirms image generation regardless of label.
# NOTE: ordinal 20 ('deepSeekR1') — if reasoningContent is NULL the actual API
# call may have used DeepSeek V3; the field reflects the UI selector, not the API.
# ---------------------------------------------------------------------------
CHAT_BOT_MODEL_MAP = {
    0: "ChatGPT 3.5",  # gpt-3.5
    1: "GPT-5",  # gpt-5
    2: "GPT-4o",  # gpt-4o
    3: "Bard / Image Gen.",  # bard (legacy; reused for image generation)
    4: "Image Generator",  # image-generator
    5: "Vision",  # vision
    6: "Google Vision",  # googleVision
    7: "Document",  # document
    8: "LLaMA 2",  # llama2
    9: "Nova",  # nova
    10: "Gemini",  # gemini
    11: "Superbot",  # superbot
    12: "Logo Generator",  # logo-generator
    13: "Tattoo Generator",  # tattoo-generator
    14: "Web Search",  # webSearch
    15: "Claude",  # claude
    16: "DeepSeek",  # deepSeek
    17: "Signature Generator",  # signature-generator
    18: "Mistral",  # mistral
    19: "Grok",  # grok
    20: "DeepSeek R1",  # deepSeekR1
    21: "AI Filter",  # aiFilter
    22: "Voice Chat",  # voiceChat
    23: "Snap & Solve",  # snapAndSolve
    24: "Study Planner",  # studyPlanner
    25: "Quiz Maker",  # quizMaker
    26: "Essay Helper",  # essayHelper
    27: "Gemini 3 Pro",  # gemini-3-pro
    28: "GPT-5.1",  # gpt-5.1
    29: "GPT-4o Mini",  # 4o-mini
}

# ---------------------------------------------------------------------------
# SQL
# One row per HistoryDetail message.
# Parent conversation context (title, model, soft-deleted) is joined from
# History. Attachment presence is detected via correlated EXISTS subqueries —
# lightweight boolean checks that avoid duplicating rows from the attachment
# tables.
# ---------------------------------------------------------------------------
QUERY = """
SELECT
    -- Message identity
    hd.id                                               AS msg_id,
    hd.UUID                                             AS msg_uuid,
    hd.historyID                                        AS conv_id,

    -- Parent conversation context (from History)
    h.UUID                                              AS conv_uuid,
    h.title                                             AS conv_title,
    h.chatBotModel                                      AS chat_bot_model,
    h.softDeleted                                       AS soft_deleted,

    -- Message content
    hd.type                                             AS msg_type,
    hd.text                                             AS msg_text,
    hd.token                                            AS token_count,
    hd.reasoningContent                                 AS reasoning_content,

    -- Message timestamps
    hd.createdAt                                        AS created_at,
    hd.lastModifiedAt                                   AS last_modified_at,

    -- Sync metadata
    hd.syncState                                        AS sync_state,
    hd.syncRetryCount                                   AS sync_retry_count,

    -- Attachment flags (correlated EXISTS — no row multiplication)
    CASE WHEN EXISTS (
        SELECT 1 FROM HistoryDetailImage i
        WHERE i.historyDetailID = hd.id
    ) THEN 1 ELSE 0 END                                 AS has_image,

    CASE WHEN EXISTS (
        SELECT 1 FROM HistoryDetailDocument d
        WHERE d.historyDetailID = hd.id
    ) THEN 1 ELSE 0 END                                 AS has_document,

    CASE WHEN EXISTS (
        SELECT 1 FROM HistoryDetailLink l
        WHERE l.historyDetailID = hd.id
    ) THEN 1 ELSE 0 END                                 AS has_link

FROM HistoryDetail hd
INNER JOIN History h
    ON h.id = hd.historyID
ORDER BY hd.historyID ASC, hd.createdAt ASC
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _convert_ms_timestamp(ms):
    """Convert a Unix millisecond timestamp to a human-readable UTC string."""
    if ms is None:
        return ""
    try:
        return datetime.datetime.utcfromtimestamp(ms / 1000).strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        )
    except (OSError, OverflowError, ValueError):
        return str(ms)


def _resolve_model(model_int):
    """Return a labelled model name, falling back to the raw integer for unknowns."""
    if model_int is None:
        return "Unknown"
    name = CHAT_BOT_MODEL_MAP.get(model_int)
    return f"{name} ({model_int})" if name else f"Unknown Model ({model_int})"


def _format_role(type_int):
    """Map HistoryDetail.type to a forensically clear role label."""
    if type_int == 0:
        return "USER"
    if type_int == 1:
        return "ASSISTANT"
    return f"UNKNOWN ({type_int})"


def _format_soft_deleted(value):
    """Return a clearly labelled string for the softDeleted field."""
    return "DELETED" if value == 1 else "No"


def _flag(value):
    """Return Yes/No for a boolean integer flag."""
    return "Yes" if value else "No"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def get_nova_chatbot_history_detail(files_found, report_folder, seeker, wrap_text):
    """
    Entry point for the nova_chatbot_history_detail artifact.

    Queries every message in HistoryDetail, enriched with parent conversation
    context from History and attachment presence flags from the three attachment
    tables. Outputs HTML report, TSV, and timeline.
    """

    for file_found in files_found:
        file_found = str(file_found)

        if not file_found.endswith("chat-ai.db"):
            continue

        try:
            db = sqlite3.connect(file_found)
            cursor = db.cursor()
            cursor.execute(QUERY)
            rows_raw = cursor.fetchall()
            db.close()

        except Exception as e:
            scripts.ilapfuncs.logfunc(
                f"[nova_chatbot_history_detail] Error reading {file_found}: {e}"
            )
            continue

        if not rows_raw:
            scripts.ilapfuncs.logfunc(
                f"[nova_chatbot_history_detail] No records found in {file_found}."
            )
            continue

        headers = [
            # --- Message identity ---
            "Msg. ID",
            "Msg. UUID",
            "Conv. ID",
            # --- Parent conversation context ---
            "Conv. UUID",
            "Conv. Title",
            "AI Model",
            "Conv. Deleted",
            # --- Message content ---
            "Role",
            "Message Text",
            "Token Count",
            "Reasoning Content",
            # --- Timestamps ---
            "Message Timestamp (UTC)",
            "Last Modified At (UTC)",
            # --- Sync metadata ---
            "Sync State",
            "Sync Retry Count",
            # --- Attachment flags ---
            "Has Image",
            "Has Document",
            "Has Link",
        ]

        rows = []
        for row in rows_raw:
            (
                msg_id,
                msg_uuid,
                conv_id,
                conv_uuid,
                conv_title,
                chat_bot_model,
                soft_deleted,
                msg_type,
                msg_text,
                token_count,
                reasoning_content,
                created_at,
                last_modified_at,
                sync_state,
                sync_retry_count,
                has_image,
                has_document,
                has_link,
            ) = row

            rows.append(
                (
                    msg_id,
                    msg_uuid or "",
                    conv_id,
                    conv_uuid or "",
                    conv_title or "",
                    _resolve_model(chat_bot_model),
                    _format_soft_deleted(soft_deleted),
                    _format_role(msg_type),
                    msg_text or "",
                    token_count if token_count is not None else "",
                    reasoning_content or "",
                    _convert_ms_timestamp(created_at),
                    _convert_ms_timestamp(last_modified_at),
                    sync_state if sync_state is not None else "",
                    sync_retry_count if sync_retry_count is not None else "",
                    _flag(has_image),
                    _flag(has_document),
                    _flag(has_link),
                )
            )

        # --- HTML report ---
        report_name = "Nova AI Chatbot - HistoryDetail"
        report = ArtifactHtmlReport(report_name)
        report.start_artifact_report(report_folder, report_name)
        report.add_script()
        report.write_artifact_data_table(
            headers,
            rows,
            file_found,
            html_escape=True,
        )
        report.end_artifact_report()

        # --- TSV output ---
        scripts.ilapfuncs.tsv(report_folder, headers, rows, report_name, file_found)

        # --- Timeline (message-level granularity, index 11 = Message Timestamp) ---
        scripts.ilapfuncs.timeline(report_folder, report_name, rows, headers)
