__artifacts_v2__ = {
    "nova_chatbot_images": {
        "name": "Nova AI Chatbot - Images (Generated & Submitted)",
        "description": (
            "Extracts all image records from the AI Chatbot - Nova app "
            "(HistoryDetailImage table). Each row represents one image and is enriched "
            "with the parent message context from HistoryDetail and the parent "
            "conversation context from History. "
            "Images are correctly identified by the parent message role: "
            "USER messages contain images submitted by the device user (e.g., vision queries); "
            "ASSISTANT messages contain images generated by the AI. "
            "Both types are stored on Firebase Storage; no local copies are predictably "
            "available offline. The report shows the prompt, metadata, and a forensic note "
            "explaining the image origin and storage behaviour. Generation state, pipeline, "
            "and style ID are included for AI‑generated images where applicable."
        ),
        "author": "Guilherme Guilherme",
        "version": "0.5",
        "date": "2026-05-03",
        "requirements": "none",
        "category": "AI Chatbot - Nova",
        "notes": (
            "Database: com.scaleup.chatai/databases/chat-ai.db. "
            "HistoryDetailImage.url stores a Firebase Storage object path. "
            "Identification of image origin is based on the parent message's type: "
            "0 = USER → user‑submitted image; 1 = ASSISTANT → AI‑generated image. "
            "The source column in HistoryDetailImage is ignored because it is often "
            "misleading (e.g., vision images are marked as source=0 but are user‑submitted). "
            "AI‑generated images are temporarily cached in cache/image_manager_disk_cache/*.0 "
            "but the filenames are SHA‑256 hashes of signed URLs containing a token not "
            "stored on the device; automatic matching is impossible. User‑submitted images "
            "are not cached locally. "
            "state: 1=Success, 0=Pending, 2=Failed (only relevant for AI‑generated). "
            "pipeline identifies the generation engine (e.g. flux_tpu). "
            "styleId references the visual style preset selected by the user. "
            "softDeleted is inherited from the parent History record."
        ),
        "paths": ("*/com.scaleup.chatai/databases/chat-ai.db",),
        "function": "get_nova_chatbot_images",
    }
}

import os
import shutil
import sqlite3
import datetime
import html as html_module
from scripts.artifact_report import ArtifactHtmlReport
import scripts.ilapfuncs

# ---------------------------------------------------------------------------
# Known mappings for the chatBotModel integer field.
# ---------------------------------------------------------------------------
CHAT_BOT_MODEL_MAP = {
    0: "ChatGPT 3.5",
    1: "GPT-5",
    2: "GPT-4o",
    3: "Bard / Image Gen.",
    4: "Image Generator",
    5: "Vision",
    6: "Google Vision",
    7: "Document",
    8: "LLaMA 2",
    9: "Nova",
    10: "Gemini",
    11: "Superbot",
    12: "Logo Generator",
    13: "Tattoo Generator",
    14: "Web Search",
    15: "Claude",
    16: "DeepSeek",
    17: "Signature Generator",
    18: "Mistral",
    19: "Grok",
    20: "DeepSeek R1",
    21: "AI Filter",
    22: "Voice Chat",
    23: "Snap & Solve",
    24: "Study Planner",
    25: "Quiz Maker",
    26: "Essay Helper",
    27: "Gemini 3 Pro",
    28: "GPT-5.1",
    29: "GPT-4o Mini",
}

IMAGE_STATE_MAP = {
    0: "Pending",
    1: "Success",
    2: "Failed",
}

# ---------------------------------------------------------------------------
# SQL (includes msg_type from HistoryDetail)
# ---------------------------------------------------------------------------
QUERY = """
SELECT
    i.id                    AS img_id,
    i.historyDetailID       AS msg_id,
    i.url                   AS img_url,
    i.prompt                AS prompt,
    i.state                 AS state,
    i.mimeType              AS mime_type,
    i.styleId               AS style_id,
    i.source                AS source,
    i.sourceUrl             AS source_url,
    i.pipeline              AS pipeline,

    hd.historyID            AS conv_id,
    hd.type                 AS msg_type,
    hd.text                 AS msg_text,
    hd.createdAt            AS msg_created_at,

    h.UUID                  AS conv_uuid,
    h.title                 AS conv_title,
    h.chatBotModel          AS chat_bot_model,
    h.softDeleted           AS soft_deleted

FROM HistoryDetailImage i
INNER JOIN HistoryDetail hd ON hd.id = i.historyDetailID
INNER JOIN History h        ON h.id = hd.historyID
ORDER BY i.id ASC
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _e(text):
    return html_module.escape(str(text)) if text else ""


def _convert_ms_timestamp(ms):
    if ms is None:
        return ""
    try:
        return datetime.datetime.utcfromtimestamp(ms / 1000).strftime(
            "%Y-%m-%d %H:%M:%S UTC"
        )
    except (OSError, OverflowError, ValueError):
        return str(ms)


def _resolve_model(model_int):
    if model_int is None:
        return "Unknown"
    name = CHAT_BOT_MODEL_MAP.get(model_int)
    return f"{name} ({model_int})" if name else f"Unknown Model ({model_int})"


def _resolve_state(state_int):
    if state_int is None:
        return ""
    label = IMAGE_STATE_MAP.get(state_int)
    return f"{label} ({state_int})" if label else f"Unknown ({state_int})"


def _format_soft_deleted(value):
    return "DELETED" if value == 1 else "No"


def _format_role(type_int):
    return {0: "USER", 1: "ASSISTANT"}.get(type_int, f"UNKNOWN ({type_int})")


def _get_image_origin(msg_type):
    """Return 'user-submitted' for msg_type=0, 'AI-generated' for msg_type=1."""
    if msg_type == 0:
        return ("user-submitted", "User‑submitted image")
    elif msg_type == 1:
        return ("ai-generated", "AI‑generated image")
    else:
        return ("unknown", "Unknown origin")


# ---------------------------------------------------------------------------
# Image file resolution (always None)
# ---------------------------------------------------------------------------
def _resolve_image_file(db_url, seeker, images_dir):
    return None


# ---------------------------------------------------------------------------
# HTML cell builder
# ---------------------------------------------------------------------------


def _build_image_cell(
    img_url, prompt, state, mime_type, pipeline, style_id, msg_type, filename
):
    """
    Build HTML cell using msg_type to determine image origin.
    """
    origin_key, origin_label = _get_image_origin(msg_type)
    cell = '<div style="font-size:12px; line-height:1.8;">'

    if prompt:
        cell += f'<div style="margin-bottom:6px;"><strong>Prompt:</strong> {_e(prompt)}</div>'

    if origin_key == "ai-generated":
        cell += (
            f'<div style="padding:8px; background:#eaf4fb; border:1px solid #aed6f1; border-radius:4px; font-size:11px; margin-bottom:6px;">'
            f"  🤖 <strong>AI‑generated image</strong><br>"
            f"  This image was created by the AI based on the user prompt. "
            f"  It is stored on Firebase Storage; a temporary local copy may exist "
            f"  in <code>cache/image_manager_disk_cache/*.0</code> but the filename "
            f"  is a hash of a signed URL that includes a token not stored on the device. "
            f"  Manual inspection of <code>.0</code> files is recommended.<br>"
            f"  <strong>Forensic action:</strong> Examine <code>.0</code> files directly as JPEG."
            f"</div>"
        )
    elif origin_key == "user-submitted":
        cell += (
            f'<div style="padding:8px; background:#fef9e7; border-left:3px solid #f39c12; font-size:11px; margin-bottom:6px;">'
            f"  📤 <strong>User‑submitted image</strong><br>"
            f"  This image was actively uploaded by the device user (e.g., as part of a vision query). "
            f"  The file content is stored on Firebase Storage and is not cached locally. "
            f"  Only the metadata record remains on the device."
            f"</div>"
        )
    else:
        cell += (
            f'<div style="padding:8px; background:#e2e3e5; border:1px solid #6c757d; border-radius:4px; font-size:11px; margin-bottom:6px;">'
            f"  ❓ <strong>Unknown image origin</strong><br>"
            f"  The parent message type is {_e(str(msg_type))} – cannot determine if user‑submitted or AI‑generated."
            f"</div>"
        )

    if pipeline:
        cell += f"<div><strong>Pipeline:</strong> {_e(pipeline)}</div>"
    if style_id is not None:
        cell += f"<div><strong>Style ID:</strong> {_e(str(style_id))}</div>"
    if mime_type:
        cell += f"<div><strong>MIME Type:</strong> {_e(mime_type)}</div>"

    cell += (
        f'<div style="margin-top:4px; font-size:10px; color:#7f8c8d;">'
        f"  <strong>Firebase path:</strong><br>"
        f'  <code style="word-break:break-all;">{_e(img_url)}</code>'
        f"</div>"
    )
    cell += "</div>"
    return cell


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def get_nova_chatbot_images(files_found, report_folder, seeker, wrap_text):
    for file_found in files_found:
        file_found = str(file_found)
        if not file_found.endswith("chat-ai.db"):
            continue

        try:
            db = sqlite3.connect(file_found)
            cursor = db.cursor()
            cursor.execute(QUERY)
            rows_raw = cursor.fetchall()
            db.close()
        except Exception as e:
            scripts.ilapfuncs.logfunc(
                f"[nova_chatbot_images] Error reading {file_found}: {e}"
            )
            continue

        if not rows_raw:
            scripts.ilapfuncs.logfunc(
                f"[nova_chbot_images] No image records found in {file_found}."
            )
            continue

        images_dir = os.path.join(report_folder, "nova_images")
        os.makedirs(images_dir, exist_ok=True)

        headers = [
            "Image ID",
            "Msg. ID",
            "Conv. ID",
            "Conv. UUID",
            "Conv. Title",
            "AI Model",
            "Conv. Deleted",
            "Msg. Role",
            "Msg. Text",
            "Msg. Timestamp (UTC)",
            "Image Preview & Metadata",
            "Prompt",
            "State",
            "Pipeline",
            "Style ID",
            "MIME Type",
            "Firebase Path",
        ]

        html_rows = []
        tsv_rows = []

        for row in rows_raw:
            (
                img_id,
                msg_id,
                img_url,
                prompt,
                state,
                mime_type,
                style_id,
                source,
                source_url,
                pipeline,
                conv_id,
                msg_type,
                msg_text,
                msg_created_at,
                conv_uuid,
                conv_title,
                chat_bot_model,
                soft_deleted,
            ) = row

            filename = _resolve_image_file(img_url, seeker, images_dir)

            common = (
                img_id,
                msg_id,
                conv_id,
                conv_uuid or "",
                conv_title or "",
                _resolve_model(chat_bot_model),
                _format_soft_deleted(soft_deleted),
                _format_role(msg_type),
                msg_text or "",
                _convert_ms_timestamp(msg_created_at),
            )

            img_cell = _build_image_cell(
                img_url,
                prompt,
                state,
                mime_type,
                pipeline,
                style_id,
                msg_type,
                filename,
            )

            # For TSV we also include the origin (derived from msg_type)
            origin_label = (
                "User-submitted"
                if msg_type == 0
                else "AI-generated"
                if msg_type == 1
                else "Unknown"
            )

            html_rows.append(
                common
                + (
                    img_cell,
                    prompt or "",
                    _resolve_state(state),
                    pipeline or "",
                    style_id if style_id is not None else "",
                    mime_type or "",
                    img_url or "",
                )
            )

            tsv_rows.append(
                common
                + (
                    "",  # no HTML in TSV
                    prompt or "",
                    _resolve_state(state),
                    pipeline or "",
                    style_id if style_id is not None else "",
                    mime_type or "",
                    img_url or "",
                )
            )

        report_name = "Nova AI Chatbot - HistoryDetailImage"
        report = ArtifactHtmlReport(report_name)
        report.start_artifact_report(report_folder, report_name)
        report.add_script()
        report.write_artifact_data_table(
            headers, html_rows, file_found, html_escape=False
        )
        report.end_artifact_report()

        scripts.ilapfuncs.tsv(report_folder, headers, tsv_rows, report_name, file_found)
        scripts.ilapfuncs.timeline(report_folder, report_name, tsv_rows, headers)
