__artifacts_v2__ = {
    "get_vlcThumbs": {
        "name": "VLC Thumbnails",
        "description": "Thumbnail images generated by VLC for its media library",
        "author": "@abrignoni, Claude",
        "creation_date": "2021-03-01",
        "last_update_date": "2026-08-31",
        "requirements": "none",
        "category": "VLC",
        "notes": "One row per thumbnail JPEG VLC generated for a media-library entry. On VLC 3.x "
                 "the thumbnails are stored in the app's external files directory at "
                 "Android/data/org.videolan.vlc/files/medialib and are named for the media id "
                 "(id_media.jpg on the tested device, VLC 3.7.1). The VLC Thumbnail Data artifact "
                 "joins these images to the media-library rows they belong to.",
        "paths": ('*/org.videolan.vlc/files/medialib/*.jpg',),
        "output_types": "standard",
        "artifact_icon": "photo",
    },
    "get_vlcThumbs_data": {
        "name": "VLC Thumbnail Data",
        "description": "VLC media library entries with their generated thumbnails",
        "author": "@abrignoni, Claude",
        "creation_date": "2021-03-01",
        "last_update_date": "2026-08-31",
        "requirements": "none",
        "category": "VLC",
        "notes": "One row per entry in the Media table of app_db/vlc_media.db, with the thumbnail "
                 "image VLC generated for it shown inline. Each media the app has seen carries a "
                 "Filename, a Type (0 Unknown, 1 Video, 2 Audio, from IMedia.h in "
                 "videolan/medialibrary), a Play Count and an Is Favorite flag. Last Played and "
                 "Insertion Date are Unix seconds and are reported as UTC. The thumbnail link is "
                 "read from the medialibrary's own tables rather than guessed: ThumbnailLinking "
                 "ties a media id to a Thumbnail row, and the Thumbnail row records the image "
                 "path in its mrl. The image file lives in the app's external files directory at "
                 "Android/data/org.videolan.vlc/files/medialib and on the tested device (VLC "
                 "3.7.1) was named for the media id; where the recorded path is missing the "
                 "id_media.jpg name is used as a fallback. On the tested device a video produced a "
                 "512x288 thumbnail that renders in this artifact, and an audio entry had no "
                 "thumbnail. A thumbnail is evidence the media was present in VLC's library, not "
                 "that it was played.",
        "paths": ('*/org.videolan.vlc/files/medialib/*.jpg', '*/org.videolan.vlc/app_db/vlc_media.db*'),
        "output_types": "standard",
        "artifact_icon": "photo",
    }
}

import datetime
import os

from scripts.ilapfuncs import artifact_processor, open_sqlite_db_readonly, check_in_media

# Media.type from videolan/medialibrary IMedia.h (Type enum): Unknown=0, Video=1, Audio=2.
MEDIA_TYPES = {0: 'Unknown', 1: 'Video', 2: 'Audio'}


def _sec_to_utc(value):
    if not value:
        return ''
    try:
        return datetime.datetime.fromtimestamp(int(value), datetime.timezone.utc)
    except (ValueError, OverflowError, OSError, TypeError):
        return ''


def _media_type(value):
    if value in MEDIA_TYPES:
        return MEDIA_TYPES[value]
    if value is None or value == '':
        return ''
    return f'{value} (as stored)'


@artifact_processor
def get_vlcThumbs(context):
    files_found = context.get_files_found()
    data_list = []
    source_path = ''
    for file_found in files_found:
        file_found = str(file_found)
        if file_found.endswith(('-wal', '-shm', '-journal')):
            continue
        if not file_found.endswith('.jpg'):
            continue
        source_path = os.path.dirname(file_found)
        name = os.path.basename(file_found)
        data_list.append((name, check_in_media(file_found, name)))

    data_headers = ('Filename', ('Thumbnail', 'media'))
    return data_headers, data_list, source_path


@artifact_processor
def get_vlcThumbs_data(context):
    files_found = context.get_files_found()
    jpg_by_name = {os.path.basename(str(f)): str(f) for f in files_found if str(f).endswith('.jpg')}
    data_list = []
    source_path = ''
    for file_found in files_found:
        file_found = str(file_found)
        if not file_found.endswith('vlc_media.db'):
            continue
        source_path = file_found
        db = open_sqlite_db_readonly(file_found)
        if db is None:
            continue
        cursor = db.cursor()
        cursor.execute('''
            SELECT m.last_played_date, m.insertion_date, m.id_media, m.filename, m.type,
                   m.play_count, m.is_favorite,
                   (SELECT t.mrl FROM ThumbnailLinking tl
                    JOIN Thumbnail t ON t.id_thumbnail = tl.thumbnail_id
                    WHERE tl.entity_id = m.id_media AND t.mrl LIKE '%.jpg'
                    LIMIT 1) AS thumb_mrl
            FROM Media m
            ORDER BY m.id_media
        ''')
        for row in cursor.fetchall():
            thumb_name = os.path.basename(row[7]) if row[7] else f'{row[2]}.jpg'
            jpg = jpg_by_name.get(thumb_name)
            thumb = check_in_media(jpg, thumb_name) if jpg else ''
            data_list.append((_sec_to_utc(row[0]), _sec_to_utc(row[1]), row[2], row[3],
                              _media_type(row[4]), row[5], row[6], thumb))
        db.close()

    data_headers = (
        ('Last Played', 'datetime'), ('Insertion Date', 'datetime'), 'ID Media', 'Filename',
        'Type', 'Play Count', 'Is Favorite', ('Thumbnail', 'media'))
    return data_headers, data_list, source_path
